server:
  port: 9000

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/time_system
    username: root
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
