server:
  port: 10011

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:10010/time_system
    username: root
    password: oHtCsDAc0wk1VApE0QEo
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB